### ISSUE TITLE
Wrong thirdperson camera angles

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-xash3d#42]
Camera looks at player from the right side instead of looking from behind.
Btw the same bug exists in original HL on goldsource.

**Comment by nekonomicon** [comment]
Type **cam_idealyaw** "1" in the console.

**Comment by FreeSlave** [comment]
Yep, it worked. Should we do anything about it or just left as is?

**Comment by a1batross** [comment]
Just left it as is. It seems Valve was did thirdperson mode for testing player animations. But for thirdperson shooter game this mode should be heavily modified and fixed.

@nekonomicon cam_idealyaw 0 is also valid. :)

**Comment by mittorn** [comment]
XashXT has fixed thirdperson code

**Comment by a1batross** [comment]
It isn't fixed so much. XadhXT only includes fix for tracing camera
position, to not let camera go outside the map. And it isn't too good,
though(camera still can go outside, because it's a point trace).

21 дек. 2017 г. 11:13 пользователь "mittorn" <notifications@github.com>
написал:

XashXT has fixed thirdperson code

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/FWGS/hlsdk-xash3d/issues/42#issuecomment-353286202>,
or mute
the thread

**Comment by nekonomicon** [comment]
@0x4E69676874466F78 а почему ты пишешь в закрытую issue?
Если считаешь это критичной проблемой можешь создать PR.

**Comment by 0x4E69676874466F78** [comment]
@nekonomicon а зачем создавать ещё одну? https://github.com/FWGS/xash3d-fwgs/issues/662#issuecomment-954750611 здесь вот мне сказали что это не баг вовсе.
Хорошо я посоветуюсь и если нам это нужно создам PR.

**Comment by lewa-j** [comment]
@0x4E69676874466F78 не он её создал. И уже тема закрыта.

**Comment by nekonomicon** [comment]
@0x4E69676874466F78 изначально в этом SDK не планировалось фиксить геймплейные баги и явные недоработки, это целиком моя инициатива.
Ну и 4 года назад я не был сопровождающим этого репозитория.
Так что поднимать закрытые issue многолетней давности плохая затея, можно создать новую и сослаться на старую.

> здесь вот мне сказали что это не баг вовсе.

Это дефолтные настройки, ты их можешь изменить в usrrconfig.cfg.
